### ISSUE TITLE
Bad Argument in Hunters:445, Vault is pass rather than file

### ISSUE THREAD

**Issue by InfectedPacket** [InfectedPacket/VxVault#3]
Exception in thread vx-hunter:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "E:\src\vxvault\VxVault\Hunters.py", line 156, in run
    new_targets = self.get_new_urls_since(datetime.now())
  File "E:\src\vxvault\VxVault\Hunters.py", line 489, in get_new_urls_since
    urls = self._get_urls_from_files(self.files)
  File "E:\src\vxvault\VxVault\Hunters.py", line 445, in _get_urls_from_files
    if (len(file) > 0 and os.path.exists(file)):
TypeError: object of type 'Vault' has no len()

**Comment by InfectedPacket** [comment]
Replaced line in Engine.py;
`_files = [self.vxvault],`
with:
`_files = [self.vxvault.file_system.get_urls_dump()]`
