### ISSUE TITLE
Index out of range exception in MdlHunter

### ISSUE THREAD

**Issue by InfectedPacket** [InfectedPacket/VxVault#5]
```
Exception in thread vx-hunter-mdl:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "E:\src\vxvault\VxVault\Hunters.py", line 158, in run
    new_targets = self.get_new_urls_since(datetime.now())
  File "E:\src\vxvault\VxVault\Hunters.py", line 222, in get_new_urls_since
    while (self.last_entry != rss_feed.entries[nb_entries] and nb_entries < _max
):
IndexError: list index out of range
```

**Comment by InfectedPacket** [comment]
```
[>] [vx-hunter-rss]: 28 entries retrieved.
```

**Comment by InfectedPacket** [comment]
Check if the counter has reached the maximum value prior to checking the last value retrieved:

```
while (self.last_entry != rss_feed.entries[nb_entries] and nb_entries < max):
```

to 

```
while (nb_entries < max and self.last_entry != rss_feed.entries[nb_entries]):
```
